"""empty message

Revision ID: 78e78ad66323
Revises: 
Create Date: 2022-04-15 18:09:13.238025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e78ad66323'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=True),
    sa.Column('caracteristicas', sa.String(length=100), nullable=True),
    sa.Column('habilidades', sa.String(length=100), nullable=True),
    sa.Column('poderes', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('herois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=True),
    sa.Column('caracteristicas', sa.String(length=100), nullable=True),
    sa.Column('habilidades', sa.String(length=100), nullable=True),
    sa.Column('poderes', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('herois')
    op.drop_table('candidatos')
    # ### end Alembic commands ###
